INSERT INTO invite_codes (code, created_by, used_by, reserved_by, reserved_until, used_at) VALUES
  ('QWER1234', NULL, NULL, NULL, NULL, NULL),
  ('ASDF5678', NULL, NULL, NULL, NULL, NULL),
  ('ZXCV9012', NULL, NULL, NULL, NULL, NULL),
  ('TYUI3456', NULL, NULL, NULL, NULL, NULL),
  ('GHJK7890', NULL, NULL, NULL, NULL, NULL),
  ('BNMA2345', NULL, NULL, NULL, NULL, NULL),
  ('PLOK6789', NULL, NULL, NULL, NULL, NULL),
  ('WERT0123', NULL, NULL, NULL, NULL, NULL),
  ('SDFG4567', NULL, NULL, NULL, NULL, NULL),
  ('XCVB8901', NULL, NULL, NULL, NULL, NULL)
ON CONFLICT (code) DO NOTHING;
